namePrefix: du-
nameSuffix: '-p-01'
commonLabels:
  environment: prd
bases:
- ../../bases
patches:
- image.yml
- replica_count.yml
configMapGenerator:
- name: index
  behavior: replace
  files:
  - configs/index.html
