apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: spm-wsh-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
